<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="rcites team" />


<title>Get started with rcites</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>



<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#header {
text-align: center;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; }  code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>

</head>

<body>




<h1 class="title toc-ignore">Get started with rcites</h1>
<h4 class="author"><em>rcites team</em></h4>
<h4 class="date"><em>10-08-2018</em></h4>



<div id="set-up-a-connection-to-the-speciescites-checklist-api" class="section level1">
<h1>Set up a connection to the Species+/CITES Checklist API</h1>
<div id="get-your-personal-token" class="section level2">
<h2>Get your personal token</h2>
<p>To set up a connection to the Species+/CITES Checklist API, an authentication token is required. Each user should obtain his or her own personal token to run the code below (see <a href="https://api.speciesplus.net/documentation" class="uri">https://api.speciesplus.net/documentation</a> for more details). To obtain a token, sign up on the <a href="http://api.speciesplus.net/users/sign_up">Species+ API website</a>.</p>
</div>
<div id="set-the-token" class="section level2">
<h2>Set the token</h2>
<p>Now, we assume that you already have a token. For illustrative purposes, we will use the generic token value <code>8QW6Qgh57sBG2k0gtt</code> for the API documentation.</p>
<p>A token is mandatory and needs to be passed to the header of all URL requests. They are three different ways to set the token in <code>rcites</code>:</p>
<ol style="list-style-type: decimal">
<li><p>set an environment variable <code>SPECIESPLUS_TOKEN</code> in <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html"><code>.Renviron</code></a> file (preferred);</p></li>
<li><p>use <code>set_token()</code> to set up the token as character string (with quotes). If not entered in the function, the token can be passed without quotes (not as character string) after a prompt. This way, the token <code>SPECIESPLUS_TOKEN</code> is interactively set up for the current R session (meaning a login will be required for the future R sessions);</p></li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(rcites)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">set_token</span>(<span class="st">&quot;8QW6Qgh57sBG2k0gtt&quot;</span>)</a></code></pre></div>
<pre><code>#&gt;  Loading rcites</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>use the <code>token</code> argument of the functions, <em>i.e.</em> the token is passed manually to each function call.</li>
</ol>
<p>Note that if set the token wrongly and wish for setting it again interactively, you must first forget the previous one with <code>forget_token()</code>.</p>
</div>
</div>
<div id="use-of-key-features" class="section level1">
<h1>Use of key features</h1>
<div id="retrieve-a-taxon-identifiers-with-spp_taxonconcept" class="section level2">
<h2>Retrieve a taxon identifiers with spp_taxonconcept()</h2>
<div id="basic-calls-to-spp_taxonconcept" class="section level3">
<h3>Basic calls to spp_taxonconcept()</h3>
<p>In order to efficiently query information from the CITES database, you first need to retrieve the unique taxon identifier <code>taxon_id</code> from the <a href="https://api.speciesplus.net/documentation/v1/taxon_concepts/index.html">Species+ taxon concept</a>. To do so, you should first call <code>spp_taxonconcept()</code> and provide the scientific name of the taxon you look for. Let us start by requesting the identifier of the African bush elephant, <em>i.e.</em> <em>Loxodonta africana</em>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">res1 &lt;-<span class="st"> </span><span class="kw">spp_taxonconcept</span>(<span class="dt">query_taxon =</span> <span class="st">&quot;Loxodonta africana&quot;</span>)</a></code></pre></div>
<p>Note that if you chose chose option 3, then the code should look like the one below:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">res1 &lt;-<span class="st"> </span><span class="kw">spp_taxonconcept</span>(<span class="dt">query_taxon =</span> <span class="st">&quot;Loxodonta africana&quot;</span>, <span class="dt">token =</span> <span class="st">&quot;8QW6Qgh57sBG2k0gtt&quot;</span>)</a></code></pre></div>
</div>
<div id="object-spp_taxonconcept" class="section level3">
<h3>Object <code>spp_taxonconcept</code></h3>
<p><code>res1</code> is an S3 object of class <code>spp_taxon</code>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">attributes</span>(res1)</a></code></pre></div>
<pre><code>#&gt;  $names
#&gt;  [1] &quot;all_id&quot;         &quot;general&quot;        &quot;higher_taxa&quot;    &quot;accepted_names&quot;
#&gt;  [5] &quot;common_names&quot;   &quot;synonyms&quot;       &quot;cites_listings&quot;
#&gt;  
#&gt;  $class
#&gt;  [1] &quot;spp_taxon&quot;
#&gt;  
#&gt;  $taxonomy
#&gt;  [1] &quot;CITES&quot;</code></pre>
<p>that contains information sorted into several data frames (see <code>?spp_taxonconcept</code>):</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">res1</a></code></pre></div>
<pre><code>#&gt;  General info - CITES ($general):
#&gt;  --------------------------------
#&gt;      id          full_name        author_year    rank name_status
#&gt;  1 4521 Loxodonta africana (Blumenbach, 1797) SPECIES           A
#&gt;             updated_at active cites_listing
#&gt;  1 2018-07-02 12:15:37   TRUE          I/II
#&gt;  
#&gt;  Classification ($higher_taxa):
#&gt;  ------------------------------
#&gt;      id  kingdom   phylum    class       order       family
#&gt;  1 4521 Animalia Chordata Mammalia Proboscidea Elephantidae
#&gt;  
#&gt;  Synonyms ($synonyms):
#&gt;  ---------------------
#&gt;      id apply.do.call.rbind..tmp.wch....2..unlist.
#&gt;  1 4521                                      37069
#&gt;  2 4521                         Loxodonta cyclotis
#&gt;  3 4521                           (Matschie, 1900)
#&gt;  4 4521                                    SPECIES
#&gt;  
#&gt;  Common names ($common_names):
#&gt;  -----------------------------
#&gt;       id                  name language
#&gt;  1  4521               Olifant       AF
#&gt;  2  4521                   Fel       AR
#&gt;  3  4521                   Fil       AZ
#&gt;  4  4521                  Slon       BE
#&gt;  5  4521                  Slon       BG
#&gt;  6  4521              Elefante       CA
#&gt;  7  4521                  Slon       CS
#&gt;  8  4521     afrikansk elefant       DA
#&gt;  9  4521               Elefant       DA
#&gt;  10 4521 Afrikanischer Elefant       DE
#&gt;  -------truncated-------
#&gt;  
#&gt;  Information available: $all_id, $general, $higher_taxa, $accepted_names, $common_names, $synonyms, $cites_listings</code></pre>
<p>For some taxa, there are more than one taxon identifier available. In <code>general</code> only <em>active</em> identifiers are listed, the the full list of identifier is available in <code>all_id</code>:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">res3 &lt;-<span class="st"> </span><span class="kw">spp_taxonconcept</span>(<span class="dt">query =</span> <span class="st">&quot;Amazilia versicolor&quot;</span>)<span class="co">#, appendix_only = TRUE)</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">res3<span class="op">$</span>general</a></code></pre></div>
<pre><code>#&gt;      id           full_name      author_year    rank name_status
#&gt;  1 3210 Amazilia versicolor (Vieillot, 1818) SPECIES           A
#&gt;             updated_at active cites_listing
#&gt;  1 2015-05-07 15:10:59   TRUE            II</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">res3<span class="op">$</span>all_id</a></code></pre></div>
<pre><code>#&gt;       id           full_name      author_year    rank name_status
#&gt;  1  3210 Amazilia versicolor (Vieillot, 1818) SPECIES           A
#&gt;  2 65789 Amazilia versicolor (Vieillot, 1818) SPECIES           S
#&gt;             updated_at active
#&gt;  1 2015-05-07 15:10:59   TRUE
#&gt;  2 2016-09-23 15:30:46  FALSE</code></pre>
<p>Also, if the taxon is not listed, a warning message should come up.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">res4 &lt;-<span class="st"> </span><span class="kw">spp_taxonconcept</span>(<span class="dt">query =</span> <span class="st">&quot;Homo Sapiens&quot;</span>)</a></code></pre></div>
<pre><code>#&gt;  Warning in spp_taxonconcept(query = &quot;Homo Sapiens&quot;): Taxon not listed.</code></pre>
</div>
<div id="custom-calls-to-spp_taxonconcept" class="section level3">
<h3>Custom calls to spp_taxonconcept()</h3>
<p><code>spp_taxonconcept()</code> includes several argument to retrieve a specific subset of information (see <code>?spp_taxonconcept</code> for more details):</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">args</span>(<span class="st">'spp_taxonconcept'</span>)</a></code></pre></div>
<pre><code>#&gt;  function (query_taxon, taxonomy = &quot;CITES&quot;, with_descendants = FALSE, 
#&gt;      language = NULL, updated_since = NULL, per_page = 500, pages = NULL, 
#&gt;      raw = FALSE, token = NULL, verbose = TRUE) 
#&gt;  NULL</code></pre>
<p>Most importantly, the argument <code>taxonomy</code> allows a selection between the two databases (CITES or CMS):</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">spp_taxonconcept</span>(<span class="dt">query =</span> <span class="st">&quot;Amazilia versicolor&quot;</span>, <span class="dt">taxonomy =</span> <span class="st">&quot;CMS&quot;</span>)</a></code></pre></div>
<pre><code>#&gt;  Warning in spp_taxonconcept(query = &quot;Amazilia versicolor&quot;, taxonomy =
#&gt;  &quot;CMS&quot;): Taxon not listed.</code></pre>
<pre><code>#&gt;  NULL</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">spp_taxonconcept</span>(<span class="dt">query =</span> <span class="st">&quot;Loxodonta africana&quot;</span>, <span class="dt">taxonomy =</span> <span class="st">&quot;CMS&quot;</span>)</a></code></pre></div>
<pre><code>#&gt;  General info - CMS ($general):
#&gt;  ------------------------------
#&gt;       id          full_name        author_year    rank name_status
#&gt;  1 11691 Loxodonta africana (Blumenbach, 1797) SPECIES           A
#&gt;             updated_at active
#&gt;  1 2018-06-05 09:19:14   TRUE
#&gt;  
#&gt;  Classification ($higher_taxa):
#&gt;  ------------------------------
#&gt;       id  kingdom   phylum    class       order       family
#&gt;  1 11691 Animalia Chordata Mammalia Proboscidea Elephantidae
#&gt;  
#&gt;  Synonyms ($synonyms):
#&gt;  ---------------------
#&gt;  data frame with 0 columns and 0 rows
#&gt;  
#&gt;  Common names ($common_names):
#&gt;  -----------------------------
#&gt;        id                  name language
#&gt;  1  11691               Olifant       AF
#&gt;  2  11691                   Fel       AR
#&gt;  3  11691                   Fil       AZ
#&gt;  4  11691                  Slon       BE
#&gt;  5  11691                  Slon       BG
#&gt;  6  11691              Elefante       CA
#&gt;  7  11691                  Slon       CS
#&gt;  8  11691     afrikansk elefant       DA
#&gt;  9  11691               Elefant       DA
#&gt;  10 11691 Afrikanischer Elefant       DE
#&gt;  -------truncated-------
#&gt;  
#&gt;  Information available: $all_id, $general, $higher_taxa, $accepted_names, $common_names, $synonyms</code></pre>
<p><code>language</code> and <code>updated_since</code> are convenient filters restrictively for the written language of common names (must be a two-letters code see <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a>) and the last update of the entries:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">spp_taxonconcept</span>(<span class="dt">query_taxon =</span> <span class="st">&quot;Loxodonta africana&quot;</span>, <span class="dt">language =</span> <span class="st">'EN'</span>,</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">  <span class="dt">updated_since =</span> <span class="st">&quot;2016-01-01&quot;</span>)</a></code></pre></div>
<pre><code>#&gt;  General info - CITES ($general):
#&gt;  --------------------------------
#&gt;      id          full_name        author_year    rank name_status
#&gt;  1 4521 Loxodonta africana (Blumenbach, 1797) SPECIES           A
#&gt;             updated_at active cites_listing
#&gt;  1 2018-07-02 12:15:37   TRUE          I/II
#&gt;  
#&gt;  Classification ($higher_taxa):
#&gt;  ------------------------------
#&gt;      id  kingdom   phylum    class       order       family
#&gt;  1 4521 Animalia Chordata Mammalia Proboscidea Elephantidae
#&gt;  
#&gt;  Synonyms ($synonyms):
#&gt;  ---------------------
#&gt;      id apply.do.call.rbind..tmp.wch....2..unlist.
#&gt;  1 4521                                      37069
#&gt;  2 4521                         Loxodonta cyclotis
#&gt;  3 4521                           (Matschie, 1900)
#&gt;  4 4521                                    SPECIES
#&gt;  
#&gt;  Common names ($common_names):
#&gt;  -----------------------------
#&gt;      id                      name language
#&gt;  1 4521          African Elephant       EN
#&gt;  2 4521 African Savannah Elephant       EN
#&gt;  
#&gt;  Information available: $all_id, $general, $higher_taxa, $accepted_names, $common_names, $synonyms, $cites_listings</code></pre>
</div>
</div>
<div id="retrieve-a-taxon-identifiers-with" class="section level2">
<h2>Retrieve a taxon identifiers with</h2>
<p>To use the four <code>spp_*</code> functions one need to use the <em>active taxon identifier</em>, so for the two species we used as example so far, this means 4521 and 3210</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">taxon identifier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Loxodonta africana</td>
<td align="left">4521</td>
</tr>
<tr class="even">
<td align="left">Amazilia versicolor</td>
<td align="left">3210</td>
</tr>
</tbody>
</table>
<div id="cites-legislation-data" class="section level3">
<h3>CITES legislation data</h3>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">spp_cites_legislation</span>(<span class="dt">taxon_id =</span> <span class="st">&quot;4521&quot;</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>#&gt;  Cites listings ($cites_listings):
#&gt;  ---------------------------------
#&gt;      id taxon_concept_id is_current appendix change_type effective_at
#&gt;  1 3666             4521       TRUE       II           +   2007-09-13
#&gt;  2 3665             4521       TRUE        I           +   2007-09-13
#&gt;  3 3645             4521       TRUE        I          R+   1990-01-18
#&gt;  
#&gt;  Cites quotas ($cites_quotas):
#&gt;  -----------------------------
#&gt;        id taxon_concept_id quota publication_date public_display is_current
#&gt;  1  20604             4521     0       2017-03-06           TRUE       TRUE
#&gt;  2  20586             4521     0       2017-03-06           TRUE       TRUE
#&gt;  3  20695             4521     0       2017-03-06           TRUE       TRUE
#&gt;  4  20696             4521     0       2017-03-06           TRUE       TRUE
#&gt;  5  20697             4521     0       2017-03-06           TRUE       TRUE
#&gt;  6  20698             4521     0       2017-03-06           TRUE       TRUE
#&gt;  7  20699             4521     0       2017-03-06           TRUE       TRUE
#&gt;  8  20700             4521     0       2017-03-06           TRUE       TRUE
#&gt;  9  20701             4521     0       2017-03-06           TRUE       TRUE
#&gt;  10 20703             4521     0       2017-03-06           TRUE       TRUE
#&gt;     unit geo_entity.iso_code2          geo_entity.name geo_entity.type
#&gt;  1  &lt;NA&gt;                   CG                    Congo         COUNTRY
#&gt;  2  &lt;NA&gt;                   AO                   Angola         COUNTRY
#&gt;  3  &lt;NA&gt;                   BW                 Botswana         COUNTRY
#&gt;  4  &lt;NA&gt;                   BF             Burkina Faso         COUNTRY
#&gt;  5  &lt;NA&gt;                   CF Central African Republic         COUNTRY
#&gt;  6  &lt;NA&gt;                   CI            Côte d'Ivoire         COUNTRY
#&gt;  7  &lt;NA&gt;                   GW            Guinea Bissau         COUNTRY
#&gt;  8  &lt;NA&gt;                   LR                  Liberia         COUNTRY
#&gt;  9  &lt;NA&gt;                   SL             Sierra Leone         COUNTRY
#&gt;  10 &lt;NA&gt;                   GA                    Gabon         COUNTRY
#&gt;  -------truncated-------
#&gt;  Field(s) not printed:  notes, url 
#&gt;  
#&gt;  Cites suspensions ($cites_suspensions):
#&gt;  ---------------------------------------
#&gt;        id taxon_concept_id start_date is_current applies_to_import
#&gt;  1  15986             &lt;NA&gt; 2013-05-16       TRUE             FALSE
#&gt;  2  17621             4521 2014-08-11       TRUE              TRUE
#&gt;  3  17620             4521 2014-08-11       TRUE              TRUE
#&gt;  4  17686             4521 2014-10-10       TRUE              TRUE
#&gt;  5  18709             4521 2010-08-16       TRUE              TRUE
#&gt;  6  15983             &lt;NA&gt; 2011-01-19       TRUE             FALSE
#&gt;  7  15971             &lt;NA&gt; 2004-07-30       TRUE             FALSE
#&gt;  8  18955             4521 2016-04-01       TRUE              TRUE
#&gt;  9  22079             &lt;NA&gt; 2018-01-30       TRUE             FALSE
#&gt;  10 22076             &lt;NA&gt; 2018-01-22       TRUE             FALSE
#&gt;     geo_entity.iso_code2             geo_entity.name geo_entity.type
#&gt;  1                    GN                      Guinea         COUNTRY
#&gt;  2                    ZW                    Zimbabwe         COUNTRY
#&gt;  3                    TZ United Republic of Tanzania         COUNTRY
#&gt;  4                    US    United States of America         COUNTRY
#&gt;  5                    ZW                    Zimbabwe         COUNTRY
#&gt;  6                    DJ                    Djibouti         COUNTRY
#&gt;  7                    SO                     Somalia         COUNTRY
#&gt;  8                    CN                       China         COUNTRY
#&gt;  9                    DJ                    Djibouti         COUNTRY
#&gt;  10                   LR                     Liberia         COUNTRY
#&gt;  -------truncated-------
#&gt;  Field(s) not printed:  notes, start_notification.name, start_notification.date, start_notification.url</code></pre>
</div>
<div id="eu-legislation-data" class="section level3">
<h3>EU legislation data</h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw">spp_eu_legislation</span>(<span class="dt">taxon_id =</span> <span class="st">&quot;4521&quot;</span>,  <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>#&gt;  EU listings ($eu_listings):
#&gt;  ---------------------------
#&gt;       id taxon_concept_id is_current annex change_type effective_at
#&gt;  1 27868             4521       TRUE     B           +   2017-02-04
#&gt;  2 27801             4521       TRUE     A           +   2017-02-04
#&gt;  
#&gt;  EU decisions ($eu_decisions):
#&gt;  -----------------------------
#&gt;        id taxon_concept_id start_date is_current eu_decision_type.name
#&gt;  1  26285             4521 2015-04-09       TRUE              Positive
#&gt;  2  25508             4521 2014-09-03       TRUE              Positive
#&gt;  3   2765             4521 2011-12-02       TRUE                    i)
#&gt;  4  11682             4521 2012-02-23       TRUE              Positive
#&gt;  5  24825             4521 2014-05-28       TRUE              Positive
#&gt;  6  27017             4521 2015-09-15       TRUE              Positive
#&gt;  7  27360             4521 2016-06-27       TRUE              Negative
#&gt;  8  30377             4521 2017-06-21       TRUE              Negative
#&gt;  9  30553             4521 2017-06-21       TRUE              Positive
#&gt;  10 30664             4521 2017-11-09       TRUE        Suspension (a)
#&gt;     eu_decision_type.type geo_entity.iso_code2             geo_entity.name
#&gt;  1       POSITIVE_OPINION                   ZW                    Zimbabwe
#&gt;  2       POSITIVE_OPINION                   BW                    Botswana
#&gt;  3             NO_OPINION                   ET                    Ethiopia
#&gt;  4       POSITIVE_OPINION                   NA                     Namibia
#&gt;  5       POSITIVE_OPINION                   ZA                South Africa
#&gt;  6       POSITIVE_OPINION                   ZM                      Zambia
#&gt;  7       NEGATIVE_OPINION                   MZ                  Mozambique
#&gt;  8       NEGATIVE_OPINION                   TZ United Republic of Tanzania
#&gt;  9       POSITIVE_OPINION                   TZ United Republic of Tanzania
#&gt;  10            SUSPENSION                   CM                    Cameroon
#&gt;     geo_entity.type start_event.name start_event.date source.code
#&gt;  1          COUNTRY       SRG 71 Soc       2015-04-09           W
#&gt;  2          COUNTRY       SRG 69 Soc       2014-09-03           W
#&gt;  3          COUNTRY       SRG 58 Soc       2011-12-02           W
#&gt;  4          COUNTRY       SRG 59 Soc       2012-02-23           W
#&gt;  5          COUNTRY       SRG 68 Soc       2014-05-28           W
#&gt;  6          COUNTRY       SRG 73 Soc       2015-09-15           W
#&gt;  7          COUNTRY       SRG 76 Soc       2016-06-27           W
#&gt;  8          COUNTRY       SRG 79 Soc       2017-06-21           W
#&gt;  9          COUNTRY       SRG 79 Soc       2017-06-21           W
#&gt;  10         COUNTRY     No 2017/1915       2017-11-09           W
#&gt;     source.name term.code term.name
#&gt;  1         Wild       TRO  trophies
#&gt;  2         Wild      &lt;NA&gt;      &lt;NA&gt;
#&gt;  3         Wild      &lt;NA&gt;      &lt;NA&gt;
#&gt;  4         Wild      &lt;NA&gt;      &lt;NA&gt;
#&gt;  5         Wild      &lt;NA&gt;      &lt;NA&gt;
#&gt;  6         Wild       TRO  trophies
#&gt;  7         Wild       TRO  trophies
#&gt;  8         Wild      &lt;NA&gt;      &lt;NA&gt;
#&gt;  9         Wild       TRO  trophies
#&gt;  10        Wild       TRO  trophies
#&gt;  Field(s) not printed:  notes, eu_decision_type.description, start_event.url</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw">spp_eu_legislation</span>(<span class="dt">taxon_id =</span> <span class="st">&quot;3210&quot;</span>, <span class="dt">scope =</span> <span class="st">&quot;all&quot;</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>#&gt;  EU listings ($eu_listings):
#&gt;  ---------------------------
#&gt;        id taxon_concept_id is_current annex change_type effective_at
#&gt;  1  17604             3210      FALSE     B           +   2012-02-14
#&gt;  2  17603             3210      FALSE     B           +   2012-12-15
#&gt;  3  17606             3210      FALSE     B           +   2009-05-22
#&gt;  4  17607             3210      FALSE     B           +   2008-04-11
#&gt;  5  17609             3210      FALSE     B           +   2003-08-30
#&gt;  6  17610             3210      FALSE     B           +   2000-12-18
#&gt;  7  17611             3210      FALSE     B           +   1997-06-01
#&gt;  8  17605             3210      FALSE     B           +   2010-08-15
#&gt;  9  17608             3210      FALSE     B           +   2005-08-22
#&gt;  10 17602             3210      FALSE     B           +   2013-08-10
#&gt;  -------truncated-------
#&gt;  
#&gt;  EU decisions ($eu_decisions):
#&gt;  -----------------------------
#&gt;  data frame with 0 columns and 0 rows</code></pre>
</div>
<div id="distribution-data" class="section level3">
<h3>Distribution data</h3>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">spp_distributions</span>(<span class="st">&quot;4521&quot;</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>#&gt;  Distributions ($distributions):
#&gt;  -------------------------------
#&gt;        id iso_code2              name    type tags
#&gt;  1   1778        ML              Mali COUNTRY     
#&gt;  2   1923        GQ Equatorial Guinea COUNTRY     
#&gt;  3   4429        RW            Rwanda COUNTRY     
#&gt;  4   4491        GH             Ghana COUNTRY     
#&gt;  5   5628        SD             Sudan COUNTRY     
#&gt;  6   6724        ET          Ethiopia COUNTRY     
#&gt;  7   8995        GA             Gabon COUNTRY     
#&gt;  8  12983        AO            Angola COUNTRY     
#&gt;  9  15554        CM          Cameroon COUNTRY     
#&gt;  10 17060        BJ             Benin COUNTRY     
#&gt;  -------truncated-------
#&gt;  
#&gt;  References ($references):
#&gt;  -------------------------
#&gt;       id                        reference
#&gt;  1  1778 Kingdon, J., Happold [truncated]
#&gt;  2  1923 Basilio, A. 1962. La [truncated]
#&gt;  3  4429 Jackson, P. 1982. El [truncated]
#&gt;  4  4429 Monfort, A. 1992. Pr [truncated]
#&gt;  5  4491 Grubb, P., Jones, T. [truncated]
#&gt;  6  4491 Jackson, P. 1982. El [truncated]
#&gt;  7  5628 Hameed, S.M.A. and E [truncated]
#&gt;  8  6724 Bolton, M. 1973. Not [truncated]
#&gt;  9  6724 Largen, M. J. and Ya [truncated]
#&gt;  10 6724 Meester, J. and Setz [truncated]
#&gt;  -------truncated-------</code></pre>
</div>
<div id="references" class="section level3">
<h3>References</h3>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw">spp_references</span>(<span class="st">&quot;4521&quot;</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>#&gt;  References ($references):
#&gt;  -------------------------
#&gt;        id                                             citation is_standard
#&gt;  1  10265 Anon. 1978. Red data book: Mammalia. IUC [truncated]       FALSE
#&gt;  2   6344 Barnes, R. F., Agnagna, M., Alers, M. P. [truncated]       FALSE
#&gt;  3  17013 Blanc, J.J., Thouless, C.R., Hart, J.A., [truncated]       FALSE
#&gt;  4   6371 Burton, M. P. 1994. Alternative projecti [truncated]       FALSE
#&gt;  5   6532 Douglas-Hamilton, I. 1987. African Eleph [truncated]       FALSE
#&gt;  6   6534 Douglas-Hamilton, I. 1987. African Eleph [truncated]       FALSE
#&gt;  7   6825 Jackson, P. 1982. Elephants and rhinos i [truncated]       FALSE
#&gt;  8   7224 Meester, J. and Setzer, H. W (eds.) 1974 [truncated]       FALSE
#&gt;  9   7609 Parker, I. and Amin, M. 1983. Ivory cris [truncated]       FALSE
#&gt;  10 19397 Parker, I.S.C. and Martin, E.B. 1982. Ho [truncated]       FALSE
#&gt;  -------truncated-------</code></pre>
</div>
</div>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
